version: "3"
services:
  web: 
    image: tanmayvaij224/mystackapp:1.0
    deploy:
      replicas: 5
      resources: 
        limits:
          cpus: "0.1"
          memory: 50m
      restart_policy: 
        condition: on-failure
    ports: 
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
  
